# -*- coding: utf-8 -*-
"""Final VLM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wq3l3pjKtP9rVwnP-s-o4U8A_xWS8GkF
"""

!pip install transformers
!pip install torchvision
!pip install timm
!pip install accelerate
!pip install Pillow

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/huggingface/nanoVLM.git
# %cd nanoVLM
!pip install torch numpy torchvision pillow datasets huggingface-hub transformers wandb
!pip install transformers torchvision accelerate
from models.vision_language_model import VisionLanguageModel
model = VisionLanguageModel.from_pretrained("lusxvr/nanoVLM-222M")

# 1. Upload images
from google.colab import files
uploaded = files.upload()
image_paths = list(uploaded.keys())

# 2. Imports
from PIL import Image
import torch
import matplotlib.pyplot as plt
from transformers import (
    BlipProcessor, BlipForConditionalGeneration,
    AutoProcessor, AutoModelForCausalLM, AutoModelForVision2Seq
)
from models.vision_language_model import VisionLanguageModel
from data.processors import get_tokenizer, get_image_processor
import pandas as pd

# 3. Set device
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

# 4. Load all models & processors
models = {}

# Load BLIP
blip_proc = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
blip_model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base").to(device)
models["BLIP"] = (blip_model, blip_proc)

# Load GIT
git_proc = AutoProcessor.from_pretrained("microsoft/git-base")
git_model = AutoModelForCausalLM.from_pretrained("microsoft/git-base").to(device)
models["GIT"] = (git_model, git_proc)

# Load SmolVLM
smol_proc = AutoProcessor.from_pretrained("HuggingFaceTB/SmolVLM-256M-Instruct")
smol_model = AutoModelForVision2Seq.from_pretrained("HuggingFaceTB/SmolVLM-256M-Instruct").to(device)
models["SmolVLM"] = (smol_model, smol_proc)

# Load nanoVLM
nano_source = "lusxvr/nanoVLM-222M"
nano_model = VisionLanguageModel.from_pretrained(nano_source).to(device).eval()
nano_tokenizer = get_tokenizer(nano_model.cfg.lm_tokenizer)
nano_img_proc = get_image_processor(nano_model.cfg.vit_img_size)
models["nanoVLM"] = (nano_model, nano_tokenizer, nano_img_proc)

# Prompt for SmolVLM and nanoVLM
prompt_text = "tell me what exactly is in the pic."

# 5. Process each image and get captions
results = []

for filename in image_paths:
    print(f"\n📷 Processing: {filename}")
    img = Image.open(filename).convert("RGB")

    # Show image
    plt.imshow(img)
    plt.axis('off')
    plt.show()

    row = {"Image": filename}

    # BLIP
    inputs = blip_proc(images=img, return_tensors="pt").to(device)
    output = blip_model.generate(**inputs)
    caption = blip_proc.decode(output[0], skip_special_tokens=True)
    row["BLIP"] = caption

    # GIT
    pixel_values = git_proc(images=img, return_tensors="pt").pixel_values.to(device)
    generated_ids = git_model.generate(pixel_values=pixel_values, max_length=50)
    caption = git_proc.batch_decode(generated_ids, skip_special_tokens=True)[0]
    row["GIT"] = caption

    # SmolVLM
    smol_prompt = smol_proc.apply_chat_template(
        [{"role": "user", "content": [{"type": "image"}, {"type": "text", "text": "describe the picture in short but detailed."}]}],
        add_generation_prompt=True
    )
    inputs = smol_proc(text=smol_prompt, images=[img], return_tensors="pt").to(device)
    generated_ids = smol_model.generate(**inputs, max_new_tokens=50)
    caption = smol_proc.batch_decode(generated_ids, skip_special_tokens=True)[0]
    row["SmolVLM"] = caption

    # nanoVLM
    template = f"Question: {prompt_text} Answer:"
    tokens = nano_tokenizer([template], return_tensors="pt")["input_ids"].to(device)
    img_tensor = nano_img_proc(img).unsqueeze(0).to(device)
    output = nano_model.generate(tokens, img_tensor, max_new_tokens=30)
    caption = nano_tokenizer.batch_decode(output, skip_special_tokens=True)[0]
    row["nanoVLM"] = caption

    results.append(row)

# 6. Display results in table
df = pd.DataFrame(results)
print("\n📝 Caption Table:")
display(df)

# 1. Upload images
from google.colab import files
uploaded = files.upload()
image_paths = list(uploaded.keys())

# 2. Imports
from PIL import Image
import torch
import matplotlib.pyplot as plt
from transformers import (
    BlipProcessor, BlipForConditionalGeneration,
    AutoProcessor, AutoModelForCausalLM, AutoModelForVision2Seq
)
from models.vision_language_model import VisionLanguageModel
from data.processors import get_tokenizer, get_image_processor
import pandas as pd

# 3. Set device
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

# 4. Load all models & processors
models = {}

# Load BLIP
blip_proc = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
blip_model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base").to(device)
models["BLIP"] = (blip_model, blip_proc)

# Load GIT
git_proc = AutoProcessor.from_pretrained("microsoft/git-base")
git_model = AutoModelForCausalLM.from_pretrained("microsoft/git-base").to(device)
models["GIT"] = (git_model, git_proc)

# Load SmolVLM
smol_proc = AutoProcessor.from_pretrained("HuggingFaceTB/SmolVLM-256M-Instruct")
smol_model = AutoModelForVision2Seq.from_pretrained("HuggingFaceTB/SmolVLM-256M-Instruct").to(device)
models["SmolVLM"] = (smol_model, smol_proc)

# Load nanoVLM
nano_source = "lusxvr/nanoVLM-222M"
nano_model = VisionLanguageModel.from_pretrained(nano_source).to(device).eval()
nano_tokenizer = get_tokenizer(nano_model.cfg.lm_tokenizer)
nano_img_proc = get_image_processor(nano_model.cfg.vit_img_size)
models["nanoVLM"] = (nano_model, nano_tokenizer, nano_img_proc)

# Prompt for SmolVLM and nanoVLM
prompt_text = "i am using you for understanding a food ingredient in the provided picture. give me only name of the food ingredient in the picture."

# 5. Process each image and get captions with inline prints
results = []

for filename in image_paths:
    print(f"\n📷 Processing: {filename}")
    img = Image.open(filename).convert("RGB")

    # Show image
    plt.imshow(img)
    plt.axis('off')
    plt.show()

    row = {"Image": filename}

    # BLIP
    inputs = blip_proc(images=img, return_tensors="pt").to(device)
    output = blip_model.generate(**inputs)
    caption = blip_proc.decode(output[0], skip_special_tokens=True)
    row["BLIP"] = caption
    print(f"🟦 BLIP says: {caption}")

    # GIT
    pixel_values = git_proc(images=img, return_tensors="pt").pixel_values.to(device)
    generated_ids = git_model.generate(pixel_values=pixel_values, max_length=50)
    caption = git_proc.batch_decode(generated_ids, skip_special_tokens=True)[0]
    row["GIT"] = caption
    print(f"🟥 GIT says: {caption}")

    # SmolVLM
    smol_prompt = smol_proc.apply_chat_template(
        [{"role": "user", "content": [{"type": "image"}, {"type": "text", "text": prompt_text}]}],
        add_generation_prompt=True
    )
    inputs = smol_proc(text=smol_prompt, images=[img], return_tensors="pt").to(device)
    generated_ids = smol_model.generate(**inputs, max_new_tokens=120)
    caption = smol_proc.batch_decode(generated_ids, skip_special_tokens=True)[0]
    row["SmolVLM"] = caption
    print(f"🟨 SmolVLM says: {caption}")

    # nanoVLM
    template = f"Question: {prompt_text} Answer:"
    tokens = nano_tokenizer([template], return_tensors="pt")["input_ids"].to(device)
    img_tensor = nano_img_proc(img).unsqueeze(0).to(device)
    output = nano_model.generate(tokens, img_tensor, max_new_tokens=30)
    caption = nano_tokenizer.batch_decode(output, skip_special_tokens=True)[0]
    row["nanoVLM"] = caption
    print(f"🟩 nanoVLM says: {caption}")

    results.append(row)

# 6. Display results in table
df = pd.DataFrame(results)
print("\n📝 Caption Table:")
display(df)